const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/incidentController');
const { authenticate } = require('../middleware/auth');
router.use(authenticate);
router.get('/',            ctrl.getAll);
router.post('/',           ctrl.create);
router.patch('/:id/status',ctrl.updateStatus);
router.delete('/:id',      ctrl.remove);
module.exports = router;
